---
title: "Voting in the Council of the EU"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Voting in the Council of the EU}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, echo = FALSE, message = FALSE, warning=FALSE, error=FALSE, include=FALSE}
# Sys.setenv(NOT_CRAN='true')
NOT_CRAN <- identical(tolower(Sys.getenv("NOT_CRAN")), "true")
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  purl = NOT_CRAN,
  eval = NOT_CRAN
)
```

Few would disagree that the Council of the European Union (EU) -- sometimes also referred to as the Council of Ministers -- is the most important decision-maker in the EU's legislative process. The Council brings together the government representatives of the Member States to, among others, negotiate EU legislation with the European Parliament as part of the ordinary legislative procedure (OLP).

Under the OLP, which is nowadays the most common type of law-making procedure, the Council should make decisions by qualified majority. In practice, it often decides by consensus, as Member States tend to avoid open disagreements. Still, enough votes are taken to give us some insight into the variation in Member State governments' behaviour. We could access these through a dedicated API maintained by the Council until May 2024.


